updated test

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,68 +1,379 @@
-version: '3.8'
+# version: "3.8"
+# services:
+#   setup:
+#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+#     volumes:
+#       - certs:/usr/share/elasticsearch/config/certs
+#     user: "root"
+    
+#     command: >
+#       bash -c '
+#         if [ ! -f config/certs/ca.zip ]; then
+#           echo "Creating CA";
+#           bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
+#           unzip config/certs/ca.zip -d config/certs;
+#         fi;
+#         if [ ! -f config/certs/certs.zip ]; then
+#           echo "Creating certs";
+#           echo -ne \
+#           "instances:\n"\
+#           "  - name: esnode1\n"\
+#           "    dns:\n"\
+#           "      - esnode1\n"\
+#           "      - localhost\n"\
+#           "    ip:\n"\
+#           "      - 127.0.0.1\n"\
+#           > config/certs/instances.yml;
+#           bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
+#           unzip config/certs/certs.zip -d config/certs;
+#         fi;
+#         echo "Setting file permissions"
+#         chown -R root:root config/certs;
+#         find . -type d -exec chmod 750 \{\} \;;
+#         find . -type f -exec chmod 640 \{\} \;;
+#         echo "Waiting for Elasticsearch availability";
+#         until curl -s --cacert config/certs/ca/ca.crt https://esnode1:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
+#         echo "Setting kibana_system password";
+#         until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://esnode1:9200/_security/user/kibana_system/_password -d "{\"password\"😕"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
+#         echo "Good to go!";
+#       '
+#     healthcheck:
+#       test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
+#       interval: 1s
+#       timeout: 5s
+#       retries: 120  
+#   esnode1:
+#     depends_on:
+#       - setup
+#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+#     volumes:
+#       - certs:/usr/share/elasticsearch/config/certs
+#       - esnode1-data:/usr/share/elasticsearch/data
+#     ports:
+#       - ${ES_PORT}:9200
+#     environment:
+#       - node.name=esnode1
+#       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
+#       - bootstrap.memory_lock=true
+#       - discovery.type=single-node
+#       - xpack.security.enabled=false
+#       - xpack.security.http.ssl.enabled=true
+#       - xpack.security.http.ssl.key=certs/esnode1/esnode1.key
+#       - xpack.security.http.ssl.certificate=certs/esnode1/esnode1.crt
+#       - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
+#       - xpack.security.http.ssl.verification_mode=certificate
+#       - xpack.security.transport.ssl.enabled=true
+#       - xpack.security.transport.ssl.key=certs/esnode1/esnode1.key
+#       - xpack.security.transport.ssl.certificate=certs/esnode1/esnode1.crt
+#       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
+#       - xpack.security.transport.ssl.verification_mode=certificate
+#       - xpack.license.self_generated.type=${LICENSE}
+#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
+#     ulimits:
+#       memlock:
+#         soft: -1
+#         hard: -1
+
+#   kibana:
+#     depends_on:
+#       - esnode1
+#     image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
+#     volumes:
+#       - certs:/usr/share/kibana/config/certs
+#       - kibana-data:/usr/share/kibana/data
+#     ports:
+#       - ${KIBANA_PORT}:5601
+#     environment:
+#       - SERVERNAME=kibana
+#       - ELASTICSEARCH_HOSTS=http://esnode1:9200
+#       - ELASTICSEARCH_USERNAME=kibana_system
+#       - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
+#       - xpack.encryptedSavedObjects.encryptionKey= 7faf2bf5f292c207aa07bfa29fd20fe9
+#       - xpack.reporting.encryptionKey= 5fc344c66733006500509ba47a2e2957
+#       - xpack.security.encryptionKey= 505338e8cd40cfcb13b06654d6bcde37
+#       - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
+#     mem_limit: ${MEM_LIMIT}
+#     healthcheck:
+#       test:
+#         [
+#           "CMD-SHELL",
+#           "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
+#         ]
+#       interval: 10s
+#       timeout: 10s
+#       retries: 120
+  
+#   database:
+#     build:
+#       context: .
+#       dockerfile: PostgresDockerfile
+#     container_name: database
+#     ports:
+#       - '5432:5432'
+#     # networks:
+#     #   - local
+#     environment:
+#       - POSTGRES_PASSWORD=postgres
+#       - POSTGRES_HOST_AUTH_METHOD=trust
+
+#   redis:
+#     image: 'redis:alpine'
+#     container_name: redis
+#     ports:
+#       - '6379:6379'
+#     # networks:
+#     #   - local
+
+#   pgsync:
+#     build:
+#       context: .
+#       dockerfile: PgsyncDockerfile
+#     container_name: pgsync
+#     environment:
+#       - PG_USER=postgres
+#       - PG_PASSWORD=postgres
+#       - PG_DATABASE=postgres
+#       - PG_HOST=database
+#       - ELASTICSEARCH_HOST=esnode1
+#       - REDIS_HOST=redis
+#     # networks:
+#     #   - local
+
+# volumes:
+#   certs:
+#     driver: local
+#   esnode1-data:
+#     driver: local
+#   kibana-data:
+#     driver: local
+# # networks:
+# #   local:
+# #     external: true
+
+version: "2.2"
+
 services:
-  elasticsearch:
-    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
-    restart: on-failure
+  setup:
+    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+    volumes:
+      - certs:/usr/share/elasticsearch/config/certs
+    user: "0"
+    command: >
+      bash -c '
+        if [ x${ELASTIC_PASSWORD} == x ]; then
+          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
+          exit 1;
+        elif [ x${KIBANA_PASSWORD} == x ]; then
+          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
+          exit 1;
+        fi;
+        if [ ! -f config/certs/ca.zip ]; then
+          echo "Creating CA";
+          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
+          unzip config/certs/ca.zip -d config/certs;
+        fi;
+        if [ ! -f config/certs/certs.zip ]; then
+          echo "Creating certs";
+          echo -ne \
+          "instances:\n"\
+          "  - name: es01\n"\
+          "    dns:\n"\
+          "      - es01\n"\
+          "      - localhost\n"\
+          "    ip:\n"\
+          "      - 127.0.0.1\n"\
+          "  - name: es02\n"\
+          "    dns:\n"\
+          "      - es02\n"\
+          "      - localhost\n"\
+          "    ip:\n"\
+          "      - 127.0.0.1\n"\
+          "  - name: es03\n"\
+          "    dns:\n"\
+          "      - es03\n"\
+          "      - localhost\n"\
+          "    ip:\n"\
+          "      - 127.0.0.1\n"\
+          > config/certs/instances.yml;
+          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
+          unzip config/certs/certs.zip -d config/certs;
+        fi;
+        echo "Setting file permissions"
+        chown -R root:root config/certs;
+        find . -type d -exec chmod 750 \{\} \;;
+        find . -type f -exec chmod 640 \{\} \;;
+        echo "Waiting for Elasticsearch availability";
+        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
+        echo "Setting kibana_system password";
+        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
+        echo "All done!";
+      '
+    healthcheck:
+      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
+      interval: 1s
+      timeout: 5s
+      retries: 120
+
+  es01:
+    depends_on:
+      setup:
+        condition: service_healthy
+    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+    volumes:
+      - certs:/usr/share/elasticsearch/config/certs
+      - esdata01:/usr/share/elasticsearch/data
     ports:
-      - "9200:9200"
+      - ${ES_PORT}:9200
     environment:
-      - xpack.security.enabled=false
-      - discovery.type=single-node
+      - node.name=es01
+      - cluster.name=${CLUSTER_NAME}
+      - cluster.initial_master_nodes=es01,es02,es03
+      - discovery.seed_hosts=es02,es03
+      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
       - bootstrap.memory_lock=true
-      - ES_JAVA_OPTS=-Xms512m -Xmx512m
+      - xpack.security.enabled=true
+      - xpack.security.http.ssl.enabled=true
+      - xpack.security.http.ssl.key=certs/es01/es01.key
+      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
+      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
+      - xpack.security.transport.ssl.enabled=true
+      - xpack.security.transport.ssl.key=certs/es01/es01.key
+      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
+      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
+      - xpack.security.transport.ssl.verification_mode=certificate
+      - xpack.license.self_generated.type=${LICENSE}
+    mem_limit: ${MEM_LIMIT}
     ulimits:
       memlock:
         soft: -1
         hard: -1
-    networks:
-      - nckh
+    healthcheck:
+      test:
+        [
+          "CMD-SHELL",
+          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
+        ]
+      interval: 10s
+      timeout: 10s
+      retries: 120
+
+  es02:
+    depends_on:
+      - es01
+    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+    volumes:
+      - certs:/usr/share/elasticsearch/config/certs
+      - esdata02:/usr/share/elasticsearch/data
+    environment:
+      - node.name=es02
+      - cluster.name=${CLUSTER_NAME}
+      - cluster.initial_master_nodes=es01,es02,es03
+      - discovery.seed_hosts=es01,es03
+      - bootstrap.memory_lock=true
+      - xpack.security.enabled=true
+      - xpack.security.http.ssl.enabled=true
+      - xpack.security.http.ssl.key=certs/es02/es02.key
+      - xpack.security.http.ssl.certificate=certs/es02/es02.crt
+      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
+      - xpack.security.transport.ssl.enabled=true
+      - xpack.security.transport.ssl.key=certs/es02/es02.key
+      - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
+      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
+      - xpack.security.transport.ssl.verification_mode=certificate
+      - xpack.license.self_generated.type=${LICENSE}
+    mem_limit: ${MEM_LIMIT}
+    ulimits:
+      memlock:
+        soft: -1
+        hard: -1
+    healthcheck:
+      test:
+        [
+          "CMD-SHELL",
+          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
+        ]
+      interval: 10s
+      timeout: 10s
+      retries: 120
+
+  es03:
+    depends_on:
+      - es02
+    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+    volumes:
+      - certs:/usr/share/elasticsearch/config/certs
+      - esdata03:/usr/share/elasticsearch/data
+    environment:
+      - node.name=es03
+      - cluster.name=${CLUSTER_NAME}
+      - cluster.initial_master_nodes=es01,es02,es03
+      - discovery.seed_hosts=es01,es02
+      - bootstrap.memory_lock=true
+      - xpack.security.enabled=true
+      - xpack.security.http.ssl.enabled=true
+      - xpack.security.http.ssl.key=certs/es03/es03.key
+      - xpack.security.http.ssl.certificate=certs/es03/es03.crt
+      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
+      - xpack.security.transport.ssl.enabled=true
+      - xpack.security.transport.ssl.key=certs/es03/es03.key
+      - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
+      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
+      - xpack.security.transport.ssl.verification_mode=certificate
+      - xpack.license.self_generated.type=${LICENSE}
+    mem_limit: ${MEM_LIMIT}
+    ulimits:
+      memlock:
+        soft: -1
+        hard: -1
+    healthcheck:
+      test:
+        [
+          "CMD-SHELL",
+          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
+        ]
+      interval: 10s
+      timeout: 10s
+      retries: 120
 
   kibana:
-    image: 'docker.elastic.co/kibana/kibana:8.2.2'
     depends_on:
-      - elasticsearch
+      es01:
+        condition: service_healthy
+      es02:
+        condition: service_healthy
+      es03:
+        condition: service_healthy
+    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
+    volumes:
+      - certs:/usr/share/kibana/config/certs
+      - kibanadata:/usr/share/kibana/data
     ports:
-      - '5601:5601'
-    networks:
-      - nckh
+      - ${KIBANA_PORT}:5601
     environment:
-      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
+      - SERVERNAME=kibana
+      - ELASTICSEARCH_HOSTS=https://es01:9200
+      - ELASTICSEARCH_USERNAME=kibana_system
+      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
+      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
+    mem_limit: ${MEM_LIMIT}
+    healthcheck:
+      test:
+        [
+          "CMD-SHELL",
+          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
+        ]
+      interval: 10s
+      timeout: 10s
+      retries: 120
 
-  database:
-    build:
-      context: .
-      dockerfile: PostgresDockerfile
-    container_name: database
-    ports:
-      - '5432:5432'
-    networks:
-      - nckh
-    environment:
-      - POSTGRES_PASSWORD=postgres
-      - POSTGRES_HOST_AUTH_METHOD=trust
-
-  redis:
-    image: 'redis:alpine'
-    container_name: redis
-    ports:
-      - '6379:6379'
-    networks:
-      - nckh
-
-  pgsync:
-    build:
-      context: .
-      dockerfile: PgsyncDockerfile
-    container_name: pgsync
-    environment:
-      - PG_USER=postgres
-      - PG_PASSWORD=postgres
-      - PG_DATABASE=postgres
-      - PG_HOST=database
-      - ELASTICSEARCH_HOST=elasticsearch
-      - REDIS_HOST=redis
-    networks:
-      - nckh
-networks:
-  nckh:
-    external: true
+volumes:
+  certs:
+    driver: local
+  esdata01:
+    driver: local
+  esdata02:
+    driver: local
+  esdata03:
+    driver: local
+  kibanadata:
+    driver: local
